sudo: required
services:
  - docker

before_install:
  - docker build -t samor0412/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true samor0412/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "udemy-docker-react"
  env: "Udemydockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-668606798224"
  bucket_path: "udemy-docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_EKY"
  secret_access_key: "$AWS_SECRET_EKY"

language: generic  

